Add basic structure for AddL and AddG commands
AY2324S1-CS2103T-W09-4/tp pull request #45
Opened 2023-10-13 00:57 UTC by MadLamprey

No functionality has been added yet, only classes have been created.

2023-10-13 02:33 UTC, sk2001git requested changes
In general just need to fix null values otherwise looks good to merge

2023-10-13 02:33 UTC, sk2001git commented on src/main/java/seedu/address/model/person/Github.java
> +    public final String value;
Should not be null , need to refer to other fields that was incorporated into person like Address, phone number.

2023-10-13 02:33 UTC, sk2001git commented on src/main/java/seedu/address/model/person/Github.java
> +        value = github;
`requireNonNull(address); `
` checkArgument(isValidAddress(address), MESSAGE_CONSTRAINTS);` - adapt accordingly, this is from address
        
   Need to have requireNonNull, and checkArgument. Might want to have a initial value as a default

2023-10-13 02:33 UTC, sk2001git commented on src/main/java/seedu/address/model/person/Github.java
> +        return value.equals(otherGithub.value);
Looks good, github links should be identical if they are in same in value

2023-10-13 02:33 UTC, sk2001git commented on src/main/java/seedu/address/model/util/SampleDataUtil.java
> +                getTagSet("friends"), null, null),
Please do not use null as a test value. 
Null should not be used

2023-10-13 02:33 UTC, sk2001git commented on src/main/java/seedu/address/model/util/SampleDataUtil.java
> +                getTagSet("friends"), null, null),
This applies for all test you have done for all the changes below

2023-10-13 12:27 UTC, ScarletBlanks commented
hey so one thing I noticed is that some parts don't operate under OOP standards and you're accessing public variables directly from the class     
     
        if (!linkedIn.value.isEmpty()) {
            builder.add("linkedin", linkedIn);
        }

        if (!github.value.isEmpty()) {
            builder.add("github", github);
        }

public class LinkedIn {

    public final String value;

}

public class Github {

    public final String value;

}

2023-10-15 06:48 UTC, sk2001git approved these changes
Test will be handed over to v1.2b 
Certain things to be addressed such as modifiers as mentioned by peng tat

otherwise looks like a good work in progress LGTM

2023-10-15 06:49 UTC, merged